# -- Site Configuration --
theme = "congo"
baseURL = "http://superseniormusic.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
