# -- Site Configuration --
theme = "congo"
baseURL = "https://jhumphries96.github.io/SuperSenior/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
