languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Super Senior"
logo = "img/supersenior_white.jpg"
# description = "Super Senior Website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 August 2022"

[author]
 name = "John Humphries"
 image = "img/author.jpg"
 headline = "Amateur Everything"
 bio = "Guitar; music; software"
 links = [
 { email = "mailto:jwhumphriesjohn@gmail.com" },
 { github = "https://github.com/jhumphries96" },
 { instagram = "https://instagram.com/jhumphries13" },
 { linkedin = "https://linkedin.com/in/humphries96" },
 { medium = "https://medium.com/@jwhumphriesjohn" },
 { youtube = "https://youtube.com/channel/UCO75A-lwK80D7UGj5Za8VaQ" },
 ]
